Completed hw 38
RomanMinevich/bookshelf pull request #1
Opened 2019-11-07 15:52 UTC by RomanMinevich

2019-11-10 19:58 UTC, boroda4436 requested changes

2019-11-10 19:58 UTC, boroda4436 commented on src/main/java/academy/mate/bookshelf/controller/BookController.java
> +@RequestMapping("/shelf")
@RomanMinevich Зазвичай коли ти будеш використовувати методи PUT, DELETE і передава и Id - то згідно принципам REST користувач (який буде викликати твій код) буде думати що він оновлює або відповідно видаляє полицю.... А це BookController і відповідно ви працюємо з книгами
```suggestion
@RequestMapping("/book")
```

2019-11-10 19:58 UTC, boroda4436 commented on src/main/java/academy/mate/bookshelf/entity/Book.java
> +    public Book(BookDto bookDto) {
@RomanMinevich В ідеалі book entity не повнна знати про існування BookDto.  Ці два класи повинні залежати один від одного. На практиці можуть бути випадки коли в тебе можуть додаватися нові і нові Dto... В такому випадку тобі прийдеться редагувати цей клас. А це буде порушення принципу Open Closed (SOLID)

2019-11-11 11:05 UTC, RomanMinevich commented on src/main/java/academy/mate/bookshelf/controller/BookController.java
> +@RequestMapping("/shelf")
Замінив

2019-11-11 11:06 UTC, RomanMinevich commented on src/main/java/academy/mate/bookshelf/entity/Book.java
> +    public Book(BookDto bookDto) {
Переробив контроллер

2019-11-12 10:38 UTC, boroda4436 approved these changes

2020-03-13 13:50 UTC, merged